---
- name: apt Install Packages
  apt:
    name: ["wget"]
- name: Installing Terraform 0.12.31
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
- name: Renaming terraform12 binary
  become: true
  command: mv /usr/local/bin/terraform /usr/local/bin/terraform12
- name: Installing Terraform 0.13.7
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/terraform/0.13.7/terraform_0.13.7_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
- name: Renaming terraform13 binary
  become: true
  command: mv /usr/local/bin/terraform /usr/local/bin/terraform13
- name: Installing Terraform 0.14.11
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
- name: Renaming terraform14 binary
  become: true
  command: mv /usr/local/bin/terraform /usr/local/bin/terraform14
- name: Installing Terraform 0.15.0
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
- name: Renaming terraform15 binary
  become: true
  command: mv /usr/local/bin/terraform /usr/local/bin/terraform15
- name: Installing Terraform 1.0.4
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/terraform/1.0.4/terraform_1.0.4_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
- name: Renaming terraform1 binary
  become: true
  command: mv /usr/local/bin/terraform /usr/local/bin/terrafo
